[package]
name = "RustyBoy"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multi_compare = "0.1.0"
sdl2 = "0.37.0"
serde = "1.0.219"
serde_json = "1.0.140"

[profile.dev]
overflow-checks = false
